version: "3"

networks:
  default:
    external:
      name: nuxt_default

services:
  nuxt:
    build: .docker
    volumes:
      - ./:/app/src
    ports:
      - "${NUXT_PORT}:${NUXT_PORT}"
    env_file:
      - .env
